Made the changes according to the guidelines to the bottom sheet example app
nisrulz/flutter-examples pull request #64
Opened 2020-10-03 11:10 UTC by Rishika-7

Made the changes according to the guidelines, the package name and the branch name to the bottom sheet example app

2020-10-03 20:55 UTC, nisrulz commented on bottom_sheet/android/app/build.gradle
> +        applicationId "com.example.project"
The package name is not fixed still 🙄

2020-10-03 20:56 UTC, nisrulz commented on bottom_sheet/android/app/src/main/kotlin/com/example/project/MainActivity.kt
> +package com.example.project
Same here.

2020-10-04 10:27 UTC, Rishika-7 commented
Corrected the package name in all the files

2020-10-05 23:24 UTC, nisrulz commented on bottom_sheet/README.md
> +A new Flutter project.
Provide description and demo gif of the example app. Check other example apps for reference.

2020-10-05 23:25 UTC, nisrulz commented on bottom_sheet/test/widget_test.dart
> +  });
Write proper tests.

2020-10-05 23:26 UTC, nisrulz commented on bottom_sheet/lib/main.dart
> +          bottom: 5.0,
For common values, use a variable.

2020-10-05 23:27 UTC, nisrulz commented on bottom_sheet/lib/main.dart
> +                topRight: const Radius.circular(10.0))),
For common values, use a variable.

2020-10-05 23:27 UTC, nisrulz commented on bottom_sheet/lib/main.dart
> +                // Add Here
Noting happens when you click on the items in Bottom Sheet. Ideally it should do something, for the least it should dismiss the Bottom Sheet.

2020-10-05 23:32 UTC, nisrulz commented on bottom_sheet/lib/main.dart
> +            ),
Each `ListTile`'s code is same. Create a function to abstract that and pass in arguments to the function so you can construct a `ListTile`.

```
ListTile getListTile(icon, iconColor, titleText) {
  return new ListTile(
    leading: new Container(
      width: 4.0,
      child: Icon(
        icon,
        color: iconColor,
        size: 24.0,
      ),
    ),
    title: new Text(
      titleText,
      style: TextStyle(
        fontSize: 14.0,
        fontWeight: FontWeight.w700,
      ),
    ),
  );
}
```

and then use as:

```
 children: <Widget>[
            getListTile(Icons.favorite, Colors.pink, "More"),
            getListTile(Icons.favorite, Colors.pink, "Favourites")
            ]
```

2020-10-05 23:32 UTC, nisrulz commented on bottom_sheet/lib/main.dart
> +class MyHomePage extends StatefulWidget {
Split your code into files.

2020-10-05 23:33 UTC, nisrulz requested changes
Please add a link of example app in the repo readme file's list.

Also address the comments in the PR.

2020-10-05 23:34 UTC, nisrulz commented
Also add a demo gif in the example directory and reference in readme. Check other example apps for reference.

2020-10-07 12:02 UTC, Rishika-7 commented
I have made the changes according to the comments.

2020-10-07 21:01 UTC, nisrulz commented
Looking better than last time. Good work @Rishika-7 ! 

I will give it a run later today.

Thank you

2020-10-07 21:05 UTC, Rishika-7 commented
Thank you I have learnt a lot! Hoping it's upto the mark :)

2020-10-08 00:55 UTC, nisrulz commented
@Rishika-7 everything looks good to me. I noticed 2 issues:

1. Inside `home.dart` file:
<img width="947" alt="Screenshot 2020-10-08 at 02 50 26" src="https://user-images.githubusercontent.com/2096087/95403004-53cd7580-0911-11eb-8d7b-23ece0d54335.png">

Solution will be to change the icon to `Icons.exit_to_app`.

2. The screenshot for demo is placed under `assets/`, which is wrong as it not a asset for the app but rather a demo gif file.
<img width="273" alt="Screenshot 2020-10-08 at 02 53 26" src="https://user-images.githubusercontent.com/2096087/95403075-7f506000-0911-11eb-8412-c4f44ba85cba.png">

If you look at other examples in the repo, you will see the demo gif just sits in the root directory of the example app itself and is named `demo.gif`.  I would suggest to follow the same and also update the link in all readme, where you reference this gif.

Rest everything works!

2020-10-08 08:23 UTC, Rishika-7 commented
I have made the changes!

2020-10-08 23:10 UTC, nisrulz commented
Great!

I think this PR is ready to merged.  Thank you for your contribution 🎉

2020-10-08 23:11 UTC, nisrulz approved these changes

2020-10-08 23:11 UTC, merged